version: '3.5'

networks: 
  phoenix-network:
    external: false


services:
  db:
    image: mysql:5.7
    container_name: phoenix-db
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - phoenix-network
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: phoenix-wordpress
    ports:
      - 8080:80
    networks:
      - phoenix-network
    volumes:
      - ./html:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

volumes:
  db_data: {}